sylius_refund_complete_refund_payment:
    path: /admin/orders/{orderNumber}/refund-payments/{id}/complete
    methods: [POST]
    defaults:
        _controller: PayPlug\SyliusPayPlugPlugin\Action\Admin\CompleteRefundPaymentAction
    prefix: /admin

sylius_refund_refund_units:
    path: /admin/orders/{orderNumber}/refund-units
    defaults:
        _controller: PayPlug\SyliusPayPlugPlugin\Action\Admin\RefundUnitsAction
    prefix: /admin
